### ISSUE TITLE
The trait bound neon::prelude::Finalize` is not satisfied

### ISSUE THREAD

**Issue by YT-Twilight** [YT-Twilight/Problems#2]
Now I'm trying to build a nodejs addon for websocket conversation.
This is the connect part of my code:
```
impl Finalize for WebSocketClient {}

fn connect(mut cx: FunctionContext) -> JsResult<JsBox<Arc<Mutex<WebSocketClient>>>> {
    let url = cx.argument::<JsString>(0)?.value(&mut cx);
    let client = Arc::new(Mutex::new(WebSocketClient::new()));
    
    let rt = Runtime::new().unwrap();
    let client_clone = Arc::clone(&client);

    rt.block_on(async {
        let mut client_guard = client_clone.lock().await;
        client_guard.connect(url);
    });
    
    Ok(cx.boxed(client_clone))
}
```
And at the last row, I got this error:
the trait bound `tokio::sync::Mutex<WebSocketClient>: neon::prelude::Finalize` is not satisfied
the following other types implement trait `neon::prelude::Finalize`:
  ()
  (T0, T1)
  (T0, T1, T2)
  (T0, T1, T2, T3)
  (T0, T1, T2, T3, T4)
  (T0, T1, T2, T3, T4, T5)
  (T0, T1, T2, T3, T4, T5, T6)
  (T0, T1, T2, T3, T4, T5, T6, T7)

I just started Rust a few days ago, so I can't find what to do with this error.
Somebody help me, please.

**Comment by WhityGhost** [comment]
Ah then it looks like the .boxed method is the issue, and it needs it's argument to implement the Finalize trait.

Probably the Arc is dereferenced for you, but the Mutex it contains doesn't implement Finalize.

This might mean that you're simply not supposed to return a Mutex (even wrapped in Arc).

There should be documentation to guide you in what you're supposed to do instead of wrapping in a Mutex, or it could be an issue with neon itself.


[docs.rs](https://docs.rs/neon/latest/neon/types/trait.Finalize.html)
[Finalize in neon::types - Rust 1](https://docs.rs/neon/latest/neon/types/trait.Finalize.html)
A trait for finalizing values owned by the main JavaScript thread.

Looking at the docs above, I can see that Finalize is implemented for std::sync::Mutex from the std library, but not tokio::sync::Mutex.

This is unfortunate because you can't implement Finalize (an external trait) for tokio::sync::Mutex (an external type) due to this the orphan rule.

I think you will be able to use a newtype as a workaround:

struct FinalizedMutex<T> {
    pub inner: tokio::sync::Mutex<T>,
}

impl<T: Finalize> Finalize for FinalizedMutex<T> {
    fn finalize<'a, C: Context<'a>>(self, cx: &mut C) {
        if let Ok(v) = self.inner.into_inner() {
            v.finalize(cx);
        }
    }
}
Which is basically saying, here's my type, that just wraps tokio's Mutex type. If the Mutex holds something that implements Finalize, then my type should implement Finalize by making the thing inside the Mutex do it's finalizing.

I copied that from [neon's impl of Finalize for std::sync::Mutex 1](https://docs.rs/neon/latest/src/neon/types_impl/boxed.rs.html#417-423) which is linked to by the docs (pro tip!).
Hopefully tokio's Mutex has the same into_inner() method. The compiler will yell at us if it doesn't :smiley:

P.S that got very complicated very quickly, but don't worry, it's a bit of an edge case and you don't really need to fully understand half of what's going on. But hopefully it's interesting, because these kinds of shenanigans can come up fairly often if you write a lot of rust code.
